openapi: "3.0.3"

info:
  title: "Shop Review Api"
  description: |
    # Feature
    - get reviews
    - post reviews
  termsOfService: "https://tastylog.com/terms/"
  contact:
    name: "customer support"
    url: "https://tastylog.com/surpport"
    email: "supoport-desc@tastyl.log"
  # TODO: SPDXについて調べる
  license:
    name: "MIT License"
    url: "https://opensource.org/license/MIT"
    
  version: "1.0.0"

servers:
  #{}で変数を埋め込める
  - url: "http://localhost:{port}"
    description: 'location development'
    variables:
      port: 
        enum: ["3000", "8080"]
        default: "3000"

paths:
  "/shops/{shopId}/reviews":
    get:
      summary: "Get specified shop reivews"
      description: "(description): Get specifed shop reviews"
      tags: ["shops"]
      # trueにすると打ち消し線が入ってこのエンドポイントは廃止されたという事を明示できる
      deprecated: false
      # パスパラメーターやクエリパラメーターをここで指定することができる
      parameters:
        - name: shopId
          # query（クエリパラメーター）, header（リクエストヘッダー）, path（パスパラメーター）, cookie(cookie)
          in: path
          description: "Shop idenftifer"
          # パスパラメーターの際には必ずTrue
          required: true
          schema: { type: string }
          example: "m4v517hg"
      responses:
        "200":
          description: "success operation"
  
  "/shps/{shopId}/reviews":
    post:
      summary: "Post specified shop review"
      description: "(description): Post specified shop reviews"
      tags: ["shops"]
      deprecated: false
      parameters:
        - name: shopId
          in: path
          description: "Shop idenftifer"
          required: true
          schema: { type: string }
          example: "m4v517hg"
          # ケースセンシティブではない
        - name: X-Api-Key
          in: header
          description: "Request user's indenfiger"
          schema: { type: string }
          example: "XXXX-XXXX-XXXX-XXXX"
        - name: token
          in: cookie
          description: "One time token"
          schema: { type: string }
          example: "XXXX-XXXX-XXXX-XXXX"
      responses:
        # 201はレスポンス内容はないけど成功しているという意味
        "201":
          description: "success operation"