openapi: "3.0.3"

info:
  title: "Shop Review Api"
  description: |
    # Feature
    - get reviews
    - post reviews
  termsOfService: "https://tastylog.com/terms/"
  contact:
    name: "customer support"
    url: "https://tastylog.com/surpport"
    email: "supoport-desc@tastyl.log"
  # TODO: SPDXについて調べる
  license:
    name: "MIT License"
    url: "https://opensource.org/license/MIT"
    
  version: "1.0.0"

servers:
  #{}で変数を埋め込める
  - url: "http://localhost:{port}"
    description: 'location development'
    variables:
      port: 
        enum: ["3000", "8080"]
        default: "3000"

paths:
  "/shops/{shopID}/reviews":
    get:
      summary: "Get specified shop reivews"
      description: "(description): Get specifed shop reviews"
      tags: ["shops"]
      # trueにすると打ち消し線が入ってこのエンドポイントは廃止されたという事を明示できる
      deprecated: false
      # パスパラメーターやクエリパラメーターをここで指定することができる
      parameters:
        - name: shopId
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: "success operation"